services:
  db:
    image: postgres:16
    restart: always
    container_name: cinematch_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cinematch_vibe
    ports:
      - "5433:5432" # <--  5433 (PC) para 5432 (Docker)
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
